
Activity 01 
Solution:
   SELECT lname, salary "Weekly Salary", dno 
   FROM employee;

Activity 02
Solution:

a)  SELECT E.LNAME, E.FNAME
    FROM EMPLOYEE E, EMPLOYEE S
    WHERE S.FNAME='Franklin' AND S.LNAME='Wong' AND E.SUPERSSN=S.SSN;

b)  SELECT LNAME, FNAME 
    FROM EMPLOYEE, DEPENDENT 
    WHERE SSN=ESSN and SSN='F' and FNAME=DEPENDENT_NAME;

c)  SELECT LNAME ,MGRSTARTDATE 
    FROM EMPLOYEE,DEPARTMENT,DEPENDENT 
    WHERE EMPLOYEE.DNO=DEPARTMENT.DNUMBER and LNAME=DEPENDENT_NAME;

d)  SELECT LNAME, FNAME,DNAME,PNAME,HOURS 
    FROM EMPLOYEE,DEPARTMENT,PROJECT,WORKS_ON 
    WHERE EMPLOYEE.DNO=PROJECT.PNUMBER GROUP BY DNO;

Activity 03
Solution:
   SELECT LAST_NAME, JOB_ID, HIRE_DATE
   FROM EMPLOYEES
   WHERE HIRE_DATE BETWEEN '20-FEB-1998' AND '01-MAY-1998'
   ORDER BY HIRE_DATE ASC;

Activity 04
Solution:
   SELECT LAST_NAME, DEPARTMENT_ID
   FROM EMPLOYEES
   WHERE DEPARTMENT_ID IN (20,50)
   ORDER BY LAST_NAME ASC;
